# Generated by Django 5.1.4 on 2024-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="mechanics",
            field=models.ManyToManyField(to="api.mechanic"),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("ph", "phone"),
                    ("email", "email"),
                    ("line", "telephone"),
                    ("fax", "fax"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mechanic",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("ER", "Engine repair"),
                    ("B", "Brakes"),
                    ("SS", "Steering and suspension"),
                    ("EP", "Engine performance"),
                ],
                max_length=20,
            ),
        ),
    ]
