# Generated by Django 5.1.4 on 2024-12-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_service_mechanics_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactinformation",
            table="contacts_information",
        ),
        migrations.AlterModelTable(
            name="lead",
            table="leads",
        ),
        migrations.AlterModelTable(
            name="mechanic",
            table="mechanics",
        ),
        migrations.AlterModelTable(
            name="service",
            table="services",
        ),
        migrations.AlterModelTable(
            name="vehicle",
            table="vehicles",
        ),
    ]
