# Generated by Django 5.1.4 on 2024-12-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_contactinformation_table_alter_lead_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="vehicle_id",
            new_name="vehicle",
        ),
    ]
