# Generated by Django 5.1.4 on 2024-12-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_vehicle_id_service_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="lead_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_informations",
                to="api.lead",
            ),
        ),
    ]
