# Generated by Django 5.1.4 on 2024-12-18 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_contactinformation_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="crated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="lead_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts_information",
                to="api.lead",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="mechanics",
            field=models.ManyToManyField(related_name="services", to="api.mechanic"),
        ),
    ]
