# Generated by Django 5.1.4 on 2024-12-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_lead_crated_at_lead_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="crated_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="service",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="api.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="api.lead",
            ),
        ),
    ]
