# Generated by Django 4.2.17 on 2024-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_crated_at_lead_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformation",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
